### ISSUE TITLE
config for surveillance station

### ISSUE THREAD

**Issue by cbrandlehner** [aficustree/homebridge-sss-platform#1]
Can you please provide more detailed documentation how to configure the surveillance station settings?

**Comment by aficustree** [comment]
something like this...

Add an action rule:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/12845992/57251708-1d027a00-7010-11e9-94b7-b1a0b711b451.png">

Then point to the homebridge instance and whatever port you've configured to listen on...
<img width="565" alt="image" src="https://user-images.githubusercontent.com/12845992/57251742-2be92c80-7010-11e9-8c3c-72431c8d741c.png">

**Comment by cbrandlehner** [comment]
thanks, works like a charm.
