### ISSUE TITLE
webhook (or other) for substitute?

### ISSUE THREAD

**Issue by jsadeli** [aficustree/homebridge-sss-platform#8]
Hi there, it appears that the SSS I have (version 8.2.7-6222) does not have "External Device" for the Action Rule. Instead, it has only the following: (1) Camera, (2) Webhook, (3) Surveillance Station, and (4) IFTTT.

I tried using Webhook and specified the same URL, but it doesn't appear to be working. Any ideas?

**Comment by jsadeli** [comment]
Never mind, it works like a charm! The URL port we should be using is the one specified in the homebridge's sss-platform config.json file.

**Comment by aficustree** [comment]
Thanks! Feel free to let me know if I can make the documentation any clearer.

**Comment by GusMuche** [comment]
Hi,

First thanks for the plugin, it work great and simple configuration. 

Like jsadeli, I've some problem to configure on my NAS. It can be more clear in the documentation if you specify the "Webhook" as Action peripheral, Method GET.

Also I've found no information about the port configuration. Do we need to configure in the NAS the port of Homebridge ? Or in Homebridge the port of the NAS ? The answer is : a new one. Just type a new port (4-5 digits) and configure the same in synology and in the plugin configuration.

It can be good to add this information in the documentation for newbies like me :-)

**Comment by aficustree** [comment]
docs updated, npm version bumped
